### ISSUE TITLE
Wallet Starts re-syncing from beginning after exiting program

### ISSUE THREAD

**Issue by odedgoro** [turtlecoin/turtle-wallet-proton#10]
Fully Synced wallet. Closed the program and started it again wallet started to sync from the start again.

**Comment by ExtraHash** [comment]
you need to save the wallet using file > save or ctrl + s, although I can implement autosave when exiting as well

**Comment by odedgoro** [comment]
Autosave should be implemented. Never used a wallet without it.

**Comment by ExtraHash** [comment]
this has been fixed in [v0.0.7-beta](https://github.com/turtlecoin/turtle-wallet-proton/releases/tag/v0.0.7-beta)
