### ISSUE TITLE
Compiling for ARM Raspberry pi 4B (again)

### ISSUE THREAD

**Issue by ibrahimk157** [turtlecoin/turtle-wallet-proton#102]
Hello,

So i made a feature request a while back on adding ARM support and it was added.

However, now I’m trying to update my wallet to a newer version, but the ARM app image is no longer there. So I attempted building it myself.

However, it gets stuck at this point:

[4/4] Building fresh packages...
[1/5] ⠈ turtlecoin-crypto
[-/5] ⠈ waiting...
[-/5] ⠁ waiting...
[4/5] ⠁ node-sass
[-/5] ⠁ waiting...

No clue what to do

**Comment by ExtraHash** [comment]
ah yep, sorry about that, I was attempting to work it into my build process so i didn't have to manually build each time for rpi and it sort of got forgotten about.

i will say that building those packages might take a VERY long time on the pi, so it's possible you just aren't waiting long enough. anyways, i'll build the wallet for you on my pi and upload it here as soon as I am able to.

**Comment by ibrahimk157** [comment]
> ah yep, sorry about that, I was attempting to work it into my build process so i didn't have to manually build each time for rpi and it sort of got forgotten about.
> 
> i will say that building those packages might take a VERY long time on the pi, so it's possible you just aren't waiting long enough. anyways, i'll build the wallet for you on my pi and upload it here as soon as I am able to.

I have tried letting it do its thing, it seems to make further progress but eventually just says “Aborted” and everything stops.

**Comment by ExtraHash** [comment]
its likely you're running out of RAM for the build process, you could try assigning a swap of around 2gb or just wait until i can build for ARM. i'll try to get that done tomorrow

**Comment by ibrahimk157** [comment]
> its likely you're running out of RAM for the build process, you could try assigning a swap of around 2gb or just wait until i can build for ARM. i'll try to get that done tomorrow

I’ve got 4GB of RAM, isn’t that plenty? If you were able to compile it a few months back on your 1GB ram pi 3, I don’t see why it’s needing a hell of a lot more than that now.

**Comment by ExtraHash** [comment]
well i did have a 2gb swap on my 1gb but yeah that's definitely plenty of RAM. without seeing the full error i can only guess at what's occurring on your end trying to build those modules

**Comment by wrkzdev** [comment]
Just need to wait until it complete :) I saw ARM needs longer time building binary. Sometimes it failed, then I just restart the build process.

**Comment by ExtraHash** [comment]
so to confirm, you were able to successfully package the appimage?

**Comment by ibrahimk157** [comment]
I’ve added 16GB swap space, just to stay safe ;)

And now i’ll try again and post the outcome.

**Comment by ibrahimk157** [comment]
> Just need to wait until it complete :) I saw ARM needs longer time building binary. Sometimes it failed, then I just restart the build process.

As I’ve said above, it eventually just says “Aborted” and everything stops. So waiting isn’t really the solution here.

**Comment by ExtraHash** [comment]
> > Just need to wait until it complete :) I saw ARM needs longer time building binary. Sometimes it failed, then I just restart the build process.
> 
> As I’ve said above, it eventually just says “Aborted” and everything stops. So waiting isn’t really the solution here.

if you're trying again, this time if you could get the full console output when it says aborted that would be helpful

**Comment by ibrahimk157** [comment]
> > > Just need to wait until it complete :) I saw ARM needs longer time building binary. Sometimes it failed, then I just restart the build process.
> > 
> > 
> > As I’ve said above, it eventually just says “Aborted” and everything stops. So waiting isn’t really the solution here.
> 
> if you're trying again, this time if you could get the full console output when it says aborted that would be helpful

Yeah that’s exactly what I’m going to do. I might need to paste into into pastebin since pasting it here could turn into a complete mess. It’s running right now.

**Comment by ExtraHash** [comment]
no problem, pastebin works or you can also drag and drop a text file right onto the github comment box

**Comment by ibrahimk157** [comment]
> no problem, pastebin works or you can also drag and drop a text file right onto the github comment box

Here you go https://pastebin.com/gmviihHc

Not sure why but I couldn’t scroll all the way up to the beginning.

**Comment by ExtraHash** [comment]
that's alright, it looks like it's electron-builder complaining again. by chance, did it output anything into the `./release` folder at all?

**Comment by wrkzdev** [comment]
I do not see any issue. I just tested to compile just now with ARM64 (1GB ram + 1.5GB swap). @ibrahimk157 maybe you can test to make from a clean build directory?

**Comment by ibrahimk157** [comment]
> that's alright, it looks like it's electron-builder complaining again. by chance, did it output anything into the `./release` folder at all?

I can’t find that directory at all

**Comment by ibrahimk157** [comment]
> I do not see any issue. I just tested to compile just now with ARM64 (1GB ram + 1.5GB swap). @ibrahimk157 maybe you can test to make from a clean build directory?

I’ve already done that several times, with the same outcome. Are you sure it’s ARM64? As far as I’m aware, it’s ARMv7.

**Comment by wrkzdev** [comment]
I am still new with ARM also. What is the output of `uname -a`?

Mine:
`Linux orangepioneplus 5.1.3-sunxi64 #5.87.190526 SMP Sun May 26 22:36:17 CEST 2019 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by ibrahimk157** [comment]
> I am still new with ARM also. What is the output of `uname -a`?
> 
> Mine:
> `Linux orangepioneplus 5.1.3-sunxi64 #5.87.190526 SMP Sun May 26 22:36:17 CEST 2019 aarch64 aarch64 aarch64 GNU/Linux`

Yup, yours is running on 64bits. Mine is on 32bits since that’s all what raspbian supports. There’s an experimental 64bit mode which I’ll try. However, it’s still in the testing phrase.

**Comment by ibrahimk157** [comment]
Same exact outcome with 64bit mode.

**Comment by ExtraHash** [comment]
Hey @ibrahimk157 , i've just uploaded an armv7 appimage to the releases page. Can you give it a try and see if it works on your system?

**Comment by ibrahimk157** [comment]
> Hey @ibrahimk157 , i've just uploaded an armv7 appimage to the releases page. Can you give it a try and see if it works on your system?

Apologies for the late response.

I just tried it out and it works perfectly! Even noticed a few new things here and there!

May I ask on how you got it to compile? I don’t want to constantly bug you to compile it for me every time a new version is released.

**Comment by ExtraHash** [comment]
First, make sure you have all dependencies listed in the readme installed (nodejs, yarn, git). Then:

1. Clone the repository
```
git clone https://github.com/turtlecoin/turtle-wallet-proton/ proton
```

2. Move into the repo directory
```
cd proton
```

3. Install the dependencies (Be sure you have yarn installed!)
```
yarn
```

4. Package for arm
```
yarn package-arm
```

It should output the AppImage in the `release` folder within the `proton` directory.


Perhaps the `package-arm` vs `package` step was what you were missing, I had forgotten it was a separate package command. Can you try these steps out and let me know if they work for you?

**Comment by ibrahimk157** [comment]
> git clone https://github.com/turtlecoin/turtle-wallet-proton/ proton

It failed, yet again, when running “yarn”. 

Here’s the output:

```
4/4] Building fresh packages...
$ electron-builder install-app-deps package.json && yarn build-dll
  • electron-builder  version=21.2.0
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=turtlecoin-crypto@3.1.3 platform=linux arch=armv7l
  • install prebuilt binary  name=turtlecoin-crypto version=3.1.3 platform=linux arch=armv7l
  • build native dependency from sources  name=turtlecoin-crypto
                                          version=3.1.3
                                          platform=linux
                                          arch=armv7l
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install info looking for cached prebuild @ /home/pi/.npm/_prebuilds/33b1a3-turtlecoin-crypto-v3.1.3-electron-v69-linux-armv7l.tar.gz
    prebuild-install http request GET https://github.com/turtlecoin/turtlecoin-crypto/releases/download/v3.1.3/turtlecoin-crypto-v3.1.3-electron-v69-linux-armv7l.tar.gz
    prebuild-install http 404 https://github.com/turtlecoin/turtlecoin-crypto/releases/download/v3.1.3/turtlecoin-crypto-v3.1.3-electron-v69-linux-armv7l.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=4.2.11 runtime=electron arch=armv7l libc= platform=linux)
    
  • rebuilding native dependency  name=turtlecoin-crypto version=3.1.3
yarn run v1.21.1
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors
Hash: 71a49e4fd2c68a1a01d8
Version: webpack 4.29.6
Time: 158ms
Built at: 12/25/2019 7:52:18 AM
              Asset      Size    Chunks             Chunk Names
renderer.dev.dll.js  15.6 KiB  renderer  [emitted]  renderer
Entrypoint renderer = renderer.dev.dll.js
[0] dll renderer 12 bytes {renderer} [built]
[@fortawesome/fontawesome-free] external "@fortawesome/fontawesome-free" 42 bytes {renderer} [built]
[bulma] external "bulma" 42 bytes {renderer} [built]
[bulma-extensions] external "bulma-extensions" 42 bytes {renderer} [built]
[connected-react-router] external "connected-react-router" 42 bytes {renderer} [built]
[core-js] external "core-js" 42 bytes {renderer} [built]
[csv-writer] external "csv-writer" 42 bytes {renderer} [built]
[devtron] external "devtron" 42 bytes {renderer} [built]
[electron-context-menu] external "electron-context-menu" 42 bytes {renderer} [built]
[electron-debug] external "electron-debug" 42 bytes {renderer} [built]
[electron-is-dev] external "electron-is-dev" 42 bytes {renderer} [built]
[electron-log] external "electron-log" 42 bytes {renderer} [built]
[file-loader] external "file-loader" 42 bytes {renderer} [built]
[history] external "history" 42 bytes {renderer} [built]
[jdenticon] external "jdenticon" 42 bytes {renderer} [built]
    + 21 hidden modules
Done in 5.33s.
Done in 491.75s.
Aborted
pi@raspberrypi:~/proton $
```

**Comment by ExtraHash** [comment]
I'm not certain that did fail, it looks like the command succeeded. I'm not sure what the "aborted" is about unless there's an error earlier in the output

**Comment by ibrahimk157** [comment]
> I'm not certain that did fail, it looks like the command succeeded. I'm not sure what the "aborted" is about unless there's an error earlier in the output

Quite interesting.

I ran yarn package-arm after that. It also ended up with “aborted” for some odd reason. However, I did find the appimage in the release directory. And it does work!

**Comment by ExtraHash** [comment]
That is odd, this is on armbian?

**Comment by ibrahimk157** [comment]
> That is odd, this is on armbian? Glad it worked though

It’s on raspbian. No clue what armbian is haha

**Comment by ExtraHash** [comment]
Ah, ok  If I get some time I will give it a shot in raspbian and see if I can figure out the aborted thing, either way, looks like we got it packaging successfully for you so I'm going to close this for now. Feel free to make a new issue if anything else pops up!
