### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by DerForstHorst** [turtlecoin/turtle-wallet-proton#103]
Resolution for smaller displays; for instance old notebooks or virtual machines

#feature request

**Comment by ExtraHash** [comment]
Hello, long time coming on this one, but this functionality has been added as of commit c8993e4

You can now use Ctrl+= and Ctrl+- to zoom in or out, and the minimum window size has been removed entirely. the wallet will assume the size of the last size and zoom factor that the wallet had when it was closed on re-opening.

This will be available in the next release, but if you'd like to use it sooner you can download the build artifact from that commit's CI build and install the one that is valid for your operating system:

https://github.com/turtlecoin/turtle-wallet-proton/suites/1004028004/artifacts/13022680

Thanks for making the feature suggestion!
