### ISSUE TITLE
Proton wallet problem

### ISSUE THREAD

**Issue by Inmyhead23** [turtlecoin/turtle-wallet-proton#104]
Error: This file is not a wallet file, or is not a wallet file type supported by this wallet version. at new Oa (file:///C:/Program%20Files/proton-wallet/resources/app.asar/app/dist/renderer.prod.js:1:233362) at Module../app/index.js (file:///C:/Program%20Files/proton-wallet/resources/app.asar/app/dist/renderer.prod.js:1:244649) at i (file:///C:/Program%20Files/proton-wallet/resources/app.asar/app/dist/renderer.prod.js:1:124) at module.exports../app/app.global.css (file:///C:/Program%20Files/proton-wallet/resources/app.asar/app/dist/renderer.prod.js:1:930) at file:///C:/Program%20Files/proton-wallet/resources/app.asar/app/dist/renderer.prod.js:1:954

Few minutes ago I was inside and works normally.

**Comment by ExtraHash** [comment]
If this is a wallet file you've created with proton, it's fairly likely you've experienced file corruption. Try deleting the config file at C:/Users/your_username/.protonwallet/config.json and see if you can open your wallet after tha

**Comment by ExtraHash** [comment]
Did you try this, and if so, what was the result?

**Comment by Inmyhead23** [comment]
It doesnt work, after that there was a problem with recovery-------- Původní zpráva --------Předmět: Re: [turtlecoin/turtle-wallet-proton] Proton wallet problem (#104)Odesílatel: ExtraHash Komu: turtlecoin/turtle-wallet-proton Kopie: Inmyhead23 ,Author Did you try this, and if so, what was the result?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/turtlecoin/turtle-wallet-proton/issues/104?email_source=notifications\u0026email_token=AM7F6PPQ7YV4KAWYBU7OIDTQ3EE4LA5CNFSM4KAMBMS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHZIEAI#issuecomment-569541121",
"url": "https://github.com/turtlecoin/turtle-wallet-proton/issues/104?email_source=notifications\u0026email_token=AM7F6PPQ7YV4KAWYBU7OIDTQ3EE4LA5CNFSM4KAMBMS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHZIEAI#issuecomment-569541121",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ExtraHash** [comment]
What do you mean problem with recovery. Most likely your wallet file got corrupted in desk somehow, so you will need to import your keys or seed.

**Comment by ExtraHash** [comment]
On disk*

**Comment by ExtraHash** [comment]
I'm going to close this due to non-response, you should be able to fix your corrupted wallet file by importing your seed phrase or keys .
