### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by Khorosho72** [turtlecoin/turtle-wallet-proton#105]
## Expected Behavior
wallet should close as commaned or directed to 

## Current Behavior
not closing

## Steps to Reproduce (for bugs)

1.
![step 1](https://user-images.githubusercontent.com/39810633/72574586-2de9d780-388f-11ea-9d32-bd8f60d40486.png)

2.
![step 2](https://user-images.githubusercontent.com/39810633/72574593-3510e580-388f-11ea-93a1-d6a8865022db.png)

3.
![step 3](https://user-images.githubusercontent.com/39810633/72574608-37733f80-388f-11ea-947c-daa3728ff9a8.png)

4.
![step 4](https://user-images.githubusercontent.com/39810633/72574613-3f32e400-388f-11ea-8529-9d6885727797.png)

## Your Environment

- Version used : Proton 2.0.0
- Operating System and version : Win 10

**Comment by ExtraHash** [comment]
This has been fixed, please download v2.0.1

**Comment by Khorosho72** [comment]
downloaded update, works as should, thanks!
