### ISSUE TITLE
Sync Status constantly spinning

### ISSUE THREAD

**Issue by nutmegminer** [turtlecoin/turtle-wallet-proton#108]
I've noticed that for the last 3 days or so (4/21/2020) the sync status does not load anymore upon wallet opening. I have verified with other node addresses that the issue still persists. 
*Windows OS

## Expected Behavior
Upon wallet load, the sync completes and loads any Txs, if any.

Looking to find out if there was any changes to the network or app version. Last autoupdate version was v.2.0.2

## Current Behavior
Sync does not complete.

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Version used : v2.0.2
- Operating System and version : Windows 10

**Comment by nutmegminer** [comment]
![proton sync](https://user-images.githubusercontent.com/47443952/80288850-73286b80-8700-11ea-9076-4b24ff5fdd7c.JPG)

**Comment by nutmegminer** [comment]
Closing issue:
trtl.bot.tips:443 & 80 do not connect

**Comment by RocksteadyTC** [comment]
So this is all cleared up?

**Comment by nutmegminer** [comment]
Yes it is. Node was the issue
