### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-proton#109]
I believe the application currently displays dates and times in the user's current timezone; however, it would be awesome if the user can select which timezone to display times in throughout the application.

I for one, like UTC but do not wish to change my system TZ to UTC.

**Comment by mrrovot** [comment]
PR #111 

![Screen Shot 2020-08-03 at 4 52 08 PM](https://user-images.githubusercontent.com/39504794/89234759-e7996300-d5a9-11ea-9cd7-49fee36a9a5d.png)

**Comment by ExtraHash** [comment]
merged in PR #111
