### ISSUE TITLE
something is failing to serialize due to electron 9 changes

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtle-wallet-proton#113]
Due to [this](https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception) breaking change, something is failing to serialize on initial startup of the wallet, and as a result we are throwing a few "object could not be cloned" errors.

I can't seem to find out where these are coming from. Something must be attached to one of the messages we send through the IPC module that is not serializable (function, class, etc). However, it appears to break nothing in the wallet that I can tel

**Comment by RocksteadyTC** [comment]
lol

**Comment by ExtraHash** [comment]
this is resolved in 886a3f2
