### ISSUE TITLE
Exchange TRTL to other coins

### ISSUE THREAD

**Issue by darkvic1** [turtlecoin/turtle-wallet-proton#118]
Hi, i would really like the ability to turn TRTL coins into other kids of crypto. That would be very helpful

**Comment by brandonlehmann** [comment]
This is not an appropriate issue for this repo. This is a TurtleCoin wallet -- not any exchange.

**Comment by crappyrules** [comment]
Leran 2 Code

**Comment by ExtraHash** [comment]
I agree, this is out of scope.
