### ISSUE TITLE
Windows version fail to sync

### ISSUE THREAD

**Issue by dragonclan1tnt** [turtlecoin/turtle-wallet-proton#119]
windows version fail to sync in windows 10

[Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404

**Comment by brandonlehmann** [comment]
This is related to #117 

You cannot use proton with v1.0.0 nodes yet. 

Try syncing against `blockapi.TurtlePay.io:443`

**Comment by ExtraHash** [comment]
yes, this still has not been upgraded for the new changes, please monitor #117  for a resolution

closing as duplicate
