### ISSUE TITLE
Rewrite configuration logic

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtle-wallet-proton#122]
The configuration logic is quite hacked together, this is due to the original refactoring from single renderer process to having the wallet backend in a separate renderer process essentially split the config into the renderer and main process configs, and then changes made by pluton introduced yet a third configuration file. we need to rip all of this out and consolidate it into one file.

**Comment by sakalli1903** [comment]
I'm sorry, I don't understand. should I wipe the wallet and reinstall it?

**Comment by sakalli1903** [comment]
both deleted and installed and restored, but the fee fell a little. doesn't the fee normally have to be 250? me fee 1720

**Comment by brandonlehmann** [comment]
Fee is set by the public node operator. Some set it dynamically to help offset their costs of providing you the convenience of not syncing the chain with a local node that you run yourself. There is no requirement for what they set.

**Comment by sakalli1903** [comment]
I get it, but it's too high, I'm making 1,000. he always wants a fee above 1,000. although I have already specified payment, my coin exe transfer has not been 6,000 my balance burned.

**Comment by brandonlehmann** [comment]
Then change to a different node and stop leeching off that operator's bandwidth...

**Comment by sakalli1903** [comment]
I'll try KuCoin instead of Coin ex

**Comment by sakalli1903** [comment]
![Adsız](https://user-images.githubusercontent.com/84450852/119008745-1b0f7780-b99b-11eb-95a3-fd7ce6927ee6.png)

although all my transfers change the same wallet
