### ISSUE TITLE
Turtlecoin wallet v3.34

### ISSUE THREAD

**Issue by aamir0000** [turtlecoin/turtle-wallet-proton#124]
I am trying to sync my Turtlecoin wallet v3.34 from last 3 days but it is stuck at 46.87 for last 3 days

Window 10
node: node.turtlepay.io:443

**Comment by ExtraHash** [comment]
Hello, can you try a different node? https://explorer.turtlecoin.lol/nodes.html

closing this for now, feel free to comment back if this does not fix the issue

**Comment by aamir0000** [comment]
Hello, yes I tried multiple nodes. Each node stucks at 46% during sync. I  also change node at 46% during sync but it does not work.
