### ISSUE TITLE
Turtlecoin wallet v3.34 Sync Problem

### ISSUE THREAD

**Issue by aamir0000** [turtlecoin/turtle-wallet-proton#125]
I am trying to sync my Turtlecoin wallet v3.34 from last 3 days but it is stuck at 46% for last 3 days

I tried multiple nodes https://explorer.turtlecoin.lol/nodes.html for sync but each node stucks at 46% during sync. I also change node at 46% during sync but it does not work.

**Comment by ExtraHash** [comment]
Hello, can you please get a log by following these instructions and post it here?

https://docs.turtlecoin.lol/guides/wallets/using-proton-wallet#how-to-get-a-log-file-and-send-it-to-the-developers

Thanks

**Comment by aamir0000** [comment]
[-1607358710725.log](https://github.com/turtlecoin/turtle-wallet-proton/files/5653916/-1607358710725.log)


I have followed your instruction, file is attached, please.

**Comment by brandonlehmann** [comment]
This is likely an issue with [this transaction](https://explorer.turtlecoin.lol/transaction.html?hash=824a716ea0384bb3f69043457869e333ac9c6f17f1c54fe9a1c9564004879e0e) which I *believe* has been resolved in [turtlecoin-wallet-backend-js v6.0.5](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/releases/tag/v6.0.5) via https://github.com/turtlecoin/turtlecoin-wallet-backend-js/commit/4b73e2dfad8155cc89b5cec0d1256b706cec7019 and thus Proton needs another dependency update :)

**Comment by aamir0000** [comment]
Can you explain what should I do? my wallet still stuck at 46%

**Comment by brandonlehmann** [comment]
Wait for @ExtraHash  to update the software :)

**Comment by ExtraHash** [comment]
@aamir0000 , can you please try the latest release with the bugfix and see if it resolves your issue?

https://github.com/turtlecoin/turtle-wallet-proton/releases/tag/v3.4.2

thanks

**Comment by aamir0000** [comment]
Now it is working, Sync has been started again. 

Thank you so much for your kind support.

**Comment by ExtraHash** [comment]
No problem, glad it is working again.
