### ISSUE TITLE
Transaction History Not Showing in Windows

### ISSUE THREAD

**Issue by vypergts** [turtlecoin/turtle-wallet-proton#126]
## Expected Behavior
Transaction history should show on Wallet after entering password and allowing sync.

## Current Behavior
No transactions showing

## Steps to Reproduce (for bugs)

1. Open Wallet app

2.  Enter password

3. Wait for sync

## Your Environment

-   Version used : 3.4.6
-   Operating System and version : Windows 10 Pro 20H2 19042.685

## Log File
[-1608322517646.log](https://github.com/turtlecoin/turtle-wallet-proton/files/5717868/-1608322517646.log)

**Comment by ExtraHash** [comment]
Hello, can you try to rescan your wallet from 0 and tell me if this still persists?

Also, ensure your public address matches what you think it should and that you don't have the wrong wallet open.

Thanks

**Comment by vypergts** [comment]
Sorry I’m traveling and trying to do this remotely. How do I make it rescan from 0?

**Comment by ExtraHash** [comment]
No problem. Click on the settings cog on top right, go to "wallet", and then click  the "rescan" button. It'll probably take a while to rescan, so let me know what happens.

**Comment by vypergts** [comment]
Resyncing from 0 worked. Thanks!

**Comment by ExtraHash** [comment]
Great, glad to hear it!

**Comment by Itsmtf** [comment]
Hello I am getting the same error. Please Tell Me What Value To Put In Rescan Wallet??

**Comment by brandonlehmann** [comment]
> Hello I am getting the same error. Please Tell Me What Value To Put In Rescan Wallet??

Try 0.
