### ISSUE TITLE
Lateset appimage issue....

### ISSUE THREAD

**Issue by DrBlackross** [turtlecoin/turtle-wallet-proton#127]
sorry, TurtleCoin Wallet v3.4.6

## Expected Behavior

fired it up but will not sync, usually appimages work no issue (with the others i have no problem)

## Current Behavior

console kicks this error (repeatedly)

DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_TurtleFGXxBw/resources/app.asar/app/dist/backendWindow.renderer.prod.js.map: 

## Possible Solution

(dont know)

## Steps to Reproduce (for bugs)
1. fire it up

2.use password

3.doesn't sync

4.tried changing the nodes to see if it was a node/syncing issue... but no.

## Your Environment

-   Version used : Ubuntu 18.04.5 LTS
-   Operating System and version :
Ubuntu 18.04.5 (64bit)
8gb ram
Kernel version 5.4.0-59-generic
AMD® Fx(tm)-8320 eight-core processor × 8  (liquid cooled)
Gnome 3.28.2
HDs    
Filesystem      Size  Used Avail Use% Mounted on               
/dev/sda1        30G  8.7G   20G  32% /
/dev/sdb2        9T  2T  8.4T  56% /home

i still have a shellnet wallet which shows there are shells in that wallet, just is nice to use the appimage wallet i have used for about 2yrs

**Comment by ExtraHash** [comment]
Can you test with the debian package and see if the issue still persists?

**Comment by DrBlackross** [comment]
k

**Comment by ExtraHash** [comment]
Thanks, I will test the AppImage on ubuntu 18 when i get some free time.

**Comment by DrBlackross** [comment]
hmmm gotta link to the debian package, i downloaded the apple disk image... or just build from source?

**Comment by ExtraHash** [comment]
Ah, one second, I didn't realize the build wasn't uploading the deb to the release page. In a few minutes it should be uploaded to the latest release.

**Comment by DrBlackross** [comment]
k, trying that

**Comment by DrBlackross** [comment]
hmmmmm

12:55:25.059 › There's an instance of the application already locked, terminating...
12:55:25.119 › Checking if program directories are present...
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

**Comment by DrBlackross** [comment]
still not syncing btw lol

**Comment by ExtraHash** [comment]
i just uploaded the deb package

**Comment by DrBlackross** [comment]
thats from the deb package

**Comment by 0des** [comment]
![image](https://user-images.githubusercontent.com/52985253/103303970-02db9380-49cd-11eb-95ff-58dbcd45987c.png)

**Comment by DrBlackross** [comment]
BEAST:~/Downloads$ ls *.deb
steam_latest.deb  turtlecoin-wallet_3.4.6_amd64.deb


drblackross@BEAST:~/Downloads$ ls *.deb -l
-rw-rw-r-- 1 drblackross drblackross  2930282 Dec  1 14:24 steam_latest.deb
-rw-rw-r-- 1 drblackross drblackross 71393484 Dec 29 12:53 turtlecoin-wallet_3.4.6_amd64.deb

**Comment by DrBlackross** [comment]
LMAO

**Comment by DrBlackross** [comment]
going to force a resync?

[Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:34 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:35 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:36 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: No blocks stored, attempting to fetch more.
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Info] [Daemon]: Failed to get wallet sync data: StatusCodeError: 404 - undefined. Lowering block count to 1
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
/tmp/.mount_TurtleFGXxBw/resources/app.asar/node_modules/turtlecoin-wallet-backend/dist/lib/Logger.js:45 [Tue, 29 Dec 2020 17:58:37 GMT] [Debug]: No blocks stored, attempting to fetch more.

**Comment by ExtraHash** [comment]
That looks like you're connecting to an out of date node.

**Comment by DrBlackross** [comment]
hmmmm then i need a listed updated node?

https://explorer.turtlecoin.lol/nodes.html

**Comment by DrBlackross** [comment]
ok, sooooo i need to update my turtlecoin node daemon as well but its at V1
https://github.com/turtlecoin/turtlecoin/releases

the proton wallet is V2, sooo will it work?
(LoL)

**Comment by DrBlackross** [comment]
oh my head hurts drank too much last night, just updated my node and i'll beat the crap out of the box later

**Comment by DrBlackross** [comment]
ok Long story short, i had to delete my local turtlecoin db folder, THEN restart the updated turtlecoin proton wallet let it resync and BOOM works.
(my node is doing the same with the checkpoint file, compression on)

**Comment by ExtraHash** [comment]
Glad to hear it’s sorted.
