### ISSUE TITLE
My Wallet Is Not Opening Getting This Error

### ISSUE THREAD

**Issue by Itsmtf** [turtlecoin/turtle-wallet-proton#129]
The File Is Not A Wallet Or Is Not a Wallet File.
I Thought That The Wallet Will Be Better Than Other Currencies Wallet, Like Raptoreum, CPUChain and others. But It Is Worst Than It. Taking Too Much Time In Syncing. Not Recommended To Use This Wallet. Tell me to solve my issue i have 2000Turtle In My Wallet

**Comment by ExtraHash** [comment]
you can re-import your private keys or seed into a new wallet, either this GUI wallet or the current cli wallet at https://github.com/turtlecoin/turtlecoin/releases
