### ISSUE TITLE
There are no payments to the wallet and there is no synchronization on the second day!!

### ISSUE THREAD

**Issue by Linkestis** [turtlecoin/turtle-wallet-proton#135]
## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

-   Version used :
-   Operating System and version :

**Comment by janpieper** [comment]
Try rescanning 😉

Settings > Wallet > Rescan Wallet

**Comment by ExtraHash** [comment]
Most likely need to change your node.
