### ISSUE TITLE
Wallet restores from wallet even if it is in my trash

### ISSUE THREAD

**Issue by johnpsar** [turtlecoin/turtle-wallet-proton#136]
OS:Ubuntu20:04
Wallet:v3.4.9

I deleted all my wallet files and reinstalled the client but it somehow picked it up and reloaded my wallet from there. I dont know if its a bug or a feature. Just letting you know

**Comment by johnpsar** [comment]
deleted =moved to trash*

**Comment by ExtraHash** [comment]
Sorry for the late reply. That is unusual. Can you double check the contents of your configuration file at ~/.protonwallet/config.json and see what is in the "walletFile" spot? It should have a filepath. Is that file present? I'm wondering if perhaps you deleted the wrong wallet file.

**Comment by johnpsar** [comment]
I ll close the issue as i changed os and lost all my files. If I find anything similar i ll report it
