### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by mstopar** [turtlecoin/turtle-wallet-proton#137]
Hello,

When i oppen my wallet, it wont sync, error ocured yesterday, 
today i installed new wersion and did restore, but it wont sync.

Please help

Best regards

**Comment by brandonlehmann** [comment]
Click the cog, click wallet, select a different node. :)

**Comment by mstopar** [comment]
Thanks, that worked, but now i only have 2000 trtl, not 2.000.000.

Its on 100% sync but show me only 2.000 trtl.
What can i do?

Best regards

**Comment by brandonlehmann** [comment]
resync the wallet

**Comment by weslleynicehash** [comment]
Não estou conseguindo sincronizar minha carneira... ja estou 4 horas esperando e não sai dos 5%

**Comment by brandonlehmann** [comment]
> Não estou conseguindo sincronizar minha carneira... ja estou 4 horas esperando e não sai dos 5%

Mudar para um nó remoto diferente

**Comment by weslleynicehash** [comment]
Ja tentei e ainda continua sincronizando e nada

**Comment by weslleynicehash** [comment]
demora muito para sincronizar???

**Comment by brandonlehmann** [comment]
> demora muito para sincronizar???

Se você não puder sincronizar com um nó remoto, sugerimos executar um nó local. Você pode baixar o software em http://latest.turtlecoin.lol e executar o TurtleCoin no arquivo que baixou.
