### ISSUE TITLE
Unable to transfer funds

### ISSUE THREAD

**Issue by Thaillie** [turtlecoin/turtle-wallet-proton#139]
## Expected Behavior
Ability to transfer entire wallet amount to an online platform.

## Current Behavior
Unable to complete transaction, insufficient unlocked funds.
Wallet sync is 100% with the public node public.turtlenode.net:443.
Debug log:
```
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Starting sendTransaction process
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Mixin not given, defaulting to mixin of 3
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Fee not given, defaulting to min fee of 1.953125 per byte
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Subwallets to take from not given, defaulting to all subwallets (address)
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Change address not given, defaulting to change address of address
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Node fee is not zero, adding node fee of 55.00 TRTL with destination of TRTLv1ioHt8Eyo8u98R63zf4X7S7bsYciAV8dTcwGqe6JVJWTwJmpZxdg6bxvXSSjeHxYtpYMU2Sg6Hq8DEXsBp5XWMmB9UxFFD
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Prevalidating transaction
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Total amount to send (Not including fee per byte): 5501
[Wed, 14 Apr 2021 13:35:22 GMT] [Debug] [Transactions]: Not enough balance to cover transaction, required: 5501, fee: 0, available: 0
```
My wallet correctly says the expected amount of available unlocked funds.

## Steps to Reproduce (for bugs)

1. Go to sent

2. Enter amount of TRTL, in my case all (also doesn't work with 50% of my wallet amount)

3. Hit sent

4. Error apears

## Your Environment

-   Version used : 3.4.9
-   Operating System and version : Win 10

**Comment by brandonlehmann** [comment]
Have you tried resyncing the wallet?

**Comment by ExtraHash** [comment]
closing for non-response, feel free to message back with the details requested if this issue persists

**Comment by Thaillie** [comment]
Ah I see I forgot to report back, the full resync seems to have fixed the issue.
Is there a way for the application to know if a full resync is needed or the local sync is invalid?

**Comment by amirbeigi1990** [comment]
i withdrawal trtl coin from coinex to trtl wallet v 3.4.9 yesterday
in coinex the status is sent and coinex has no problem
my balance in trtl wallet is still 0
and wallet sync is 98% . . .
please help
