### ISSUE TITLE
Não estou conseguindo acessar minha carteira da turtecoin ela não sincroniza, ja tentei trocar a no. ja tentei acessar pelo android e nada fica sincronizano e ja se passou dois dias e nada, gostaria de saber o que esta acontecendo.

### ISSUE THREAD

**Issue by weslleynicehash** [turtlecoin/turtle-wallet-proton#140]
## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

-   Version used :
-   Operating System and version :

**Comment by brandonlehmann** [comment]
Tente alterar o nó remoto que você está usando ou execute seu próprio nó local.

**Comment by weslleynicehash** [comment]
ja tentei e não adiantou,

**Comment by brandonlehmann** [comment]
> ja tentei e não adiantou,

Você tentou executar um nó local? Você baixou o software principal de http://latest.turtlecoin.lol, executou o TurtleCoind e permitiu que o nó sincronizasse com seu sistema localmente? Se você fez isso, não há razão para que ele não sincronize a partir desse nó local, a menos que você também não tenha definido o nó na carteira para `127.0.0.1: 11898`

**Comment by weslleynicehash** [comment]
Tenteis todos esse nodes:
turtle.imhard4.men:11898
TRTLnode.ddns.net:11898
turtle.cryptoarm.nl:11898
cz.turtlecoin4ever.online:11898
ro.turtlecoin4ever.online:11898
ro.turtlecoin4ever.online:11898
trtl.bot.tips:443
node.faircryptocoins.xyz:11898
node.faircryptocoins.xyz:443
turtlenode.co:11898
trtl.harry.games:11898
nodes.hashvault.pro:11898
nodes.hashvault.pro:11898
.
.
.

**Comment by brandonlehmann** [comment]
> Tenteis todos esse nodes:
> turtle.imhard4.men:11898
> TRTLnode.ddns.net:11898
> turtle.cryptoarm.nl:11898
> cz.turtlecoin4ever.online:11898
> ro.turtlecoin4ever.online:11898
> ro.turtlecoin4ever.online:11898
> trtl.bot.tips:443
> node.faircryptocoins.xyz:11898
> node.faircryptocoins.xyz:443
> turtlenode.co:11898
> trtl.harry.games:11898
> nodes.hashvault.pro:11898
> nodes.hashvault.pro:11898
> .
> .
> .

Esses são todos nós remotos. Novamente, tente executar e sincronizar um nó local por meio das instruções que dei a você. Nem todos terão uma grande experiência de sincronização com nós remotos. Muito provavelmente, você precisará sincronizar um nó sozinho.

**Comment by weslleynicehash** [comment]
entendi, irei tentar aqui novamente, mais como faço para sincroniar um nó sozinho, terei que ir testando um por um desses???

**Comment by brandonlehmann** [comment]
> entendi, irei tentar aqui novamente, mais como faço para sincroniar um nó sozinho, terei que ir testando um por um desses???

Vá para http://latest.turtlecoin.lol e baixe o software principal como eu disse antes. Em seguida, execute o TurtleCoind e espere que ele diga que está totalmente sincronizado. Então, e somente então, você poderá sincronizar sua carteira com ele. Vai levar algum tempo. Por favor, seja paciente.

**Comment by weslleynicehash** [comment]
certo irei remover do me sistema e fazer o download novamente, obrigado

**Comment by brandonlehmann** [comment]
> certo irei remover do me sistema e fazer o download novamente, obrigado

Remover e baixar esta carteira novamente não irá ajudá-lo. Você deve sincronizar a cadeia conforme eu dei as instruções e então você poderá sincronizar sua carteira. A carteira muito provavelmente nunca sincronizará até que você sincronize um nó local primeiro, se nenhum dos nós remotos estiver funcionando para você.

**Comment by ExtraHash** [comment]
Este problema foi resolvido com a sincronização de um nó local?
