### ISSUE TITLE
Payment ID lack of

### ISSUE THREAD

**Issue by muratgurcan61** [turtlecoin/turtle-wallet-proton#142]
05.02.2021 Date 2000 TRTL forgot the bd87e5b3bd7fc116b97445bad9fb139fb5d3ae34e5f297d970b1b4ab9a5fba0d code and date of 01/05/2021 0319ca57b8910674f38a53b21ac6225f128ae9dc777e31bf1d06fc294f76b6ba code with the code 1000 TRTL kuco of writing my wallet with IDs when sending peyment TRTLv2xgnXYJBqb7BuX2MwFZg42hfNDxrK9Y7kjZBNHuZRM17sJSEvQQK8BDhb3Nra48dvXydwZEjA7gWKNwLRJpE7Rw4DXjQqJ code. I request my 3000 TRTL coin to be transferred to my kucoin account
![Ekran Görüntüsü (43)](https://user-images.githubusercontent.com/83544416/116816971-ef079000-ab6c-11eb-9c13-d66220cbcc57.png)

**Comment by brandonlehmann** [comment]
If you forgot the payment ID you will need to contact the exchange and see if they will credit your account. There is nothing that the developer of this wallet can do for you.

**Comment by muratgurcan61** [comment]
They asked for my payment id. Where will I learn tuutlecoin wallet id?


[cid:1cadb126-b0d3-4a36-9a53-e29fd06483be]
Şant. Şefi / İnş. Müh.
Murat GÜRCAN
05537076161


[cid:914124eb-9ea5-4815-be4d-75eee84b9c16]
COKCOG DA TASARIM ADINA YOK YOK!
WHATSAPP
+7 909 609 6195

________________________________
Gönderen: Brandon Lehmann ***@***.***>
Gönderildi: 2 Mayıs 2021 Pazar 18:07
Kime: turtlecoin/turtle-wallet-proton ***@***.***>
Bilgi: muratgurcan61 ***@***.***>; Author ***@***.***>
Konu: Re: [turtlecoin/turtle-wallet-proton] Payment ID lack of (#142)


If you forgot the payment ID you will need to contact the exchange and see if they will credit your account. There is nothing that the developer of this wallet can do for you.

**Comment by brandonlehmann** [comment]
You don’t need a payment ID to receive funds to a personal wallet.

**Comment by muratgurcan61** [comment]
Turtlecoin id was requested because the money I sent to the kucoin account was not sent. where to find out payment id



[cid:a1c98423-b868-4dc9-b335-b5827889cba3]
Şant. Şefi / İnş. Müh.
Murat GÜRCAN
05537076161


[cid:b77c68a8-8e34-4028-93cf-57126edbaec4]
COKCOG DA TASARIM ADINA YOK YOK!
WHATSAPP
+7 909 609 6195

________________________________
Gönderen: Brandon Lehmann ***@***.***>
Gönderildi: 2 Mayıs 2021 Pazar 18:11
Kime: turtlecoin/turtle-wallet-proton ***@***.***>
Bilgi: muratgurcan61 ***@***.***>; Author ***@***.***>
Konu: Re: [turtlecoin/turtle-wallet-proton] Payment ID lack of (#142)


You don’t need a payment ID to receive funds to a personal wallet.

**Comment by brandonlehmann** [comment]
In your exchange account with their deposit instructions. They make it very clear the payment ID they provide you needs to be included in the transaction. Please contact them for further support.
