### ISSUE TITLE
where is my 1000 TRTL. You did not pay me 

### ISSUE THREAD

**Issue by TurtleDi** [turtlecoin/turtle-wallet-proton#143]
## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

-   Version used :
-   Operating System and version :

**Comment by ExtraHash** [comment]
I would suggest contacting the support of whoever was meant to send you the 1000 trtl, this issue tracker is for bugs in the wallet software which runs on your own computer.

**Comment by TurtleDi** [comment]
hello.. i mining TRTL coin and i earned 3000 TRTL . 2000 TRTL paid but 1000 TRTL did not received from my wallet. what can i do

**Comment by ExtraHash** [comment]
You should contact the pool you are mining on for support. Is the transaction hash on the block explorer? If so, try re-scanning your wallet.

**Comment by TurtleDi** [comment]
Yes i have transaction hash on the block explorer

iPhone’umdan gönderildi

**Comment by TurtleDi** [comment]
How can i contact with my pool? i have transaction hash on the block Explorer but after 4 days no payment..  Windows 10 için Posta ile gönderildi Kimden: ExtraHashGönderilme: 5 Mayıs 2021 Çarşamba 02:40Kime: turtlecoin/turtle-wallet-protonBilgi: TurtleDi; AuthorKonu: Re: [turtlecoin/turtle-wallet-proton] where is my 1000 TRTL. You did not pay me (#143) You should contact the pool you are mining on for support. Is the transaction hash on the block explorer? If so, try re-scanning your wallet.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
