### ISSUE TITLE
solo blocks not properly syncing

### ISSUE THREAD

**Issue by halimuygun** [turtlecoin/turtle-wallet-proton#145]
Hello! I have solo mined turtlecoin and i found a block. But i cant see reward and transaction in my wallet. On settings, i turn on coinbase transactions. I checked this block with my adress and private view key on block explorer but still i dont have my reward.

And this is very interesting; Im using TonChan wallet. When block synchronizing arrived my block height, it stops and dont synchronize anymore? I rewinded wallet many times. What is wrong i dont understand?

Transaction : 6557f358402ee02e898683a00a8a93060d987b2d0fe3a371cda2d1b2e88170ce
Block Height : 3,544,956

Version Used : Proton Wallet (v3.4.9)

* I copied this issue from: https://github.com/turtlecoin/turtlecoin-mobile-wallet/issues/146

* Its already working on Zedwallet and it fixed on mobile wallet. But proton-wallet still has this bug.

**Comment by brandonlehmann** [comment]
https://docs.turtlecoin.lol/guides/wallets/restoring-your-wallet-from-a-specific-block-height

**Comment by ExtraHash** [comment]
Just to be clear, you have already enabled scan coinbase transactions and rescanned the wallet from the height of your found block or previous?

**Comment by ExtraHash** [comment]
closing due to non-response

**Comment by halimuygun** [comment]
> Just to be clear, you have already enabled scan coinbase transactions and rescanned the wallet from the height of your found block or previous?

Yes already i did. You can read conversations on this issue: https://github.com/turtlecoin/turtlecoin-mobile-wallet/issues/146

**Comment by ExtraHash** [comment]
I see, thanks for the link, I'll likely have to update the js backend library if that bug has been fixed
