### ISSUE TITLE
Wallet not synchronizing

### ISSUE THREAD

**Issue by pinpoint-forest** [turtlecoin/turtle-wallet-proton#147]
## Expected Behavior

Expect to see my funds on my wallet and also see a full synchronized wallet.

## Current Behavior

When I open and close the wallet the total sync % changes from 99.9 to 99.2 to 99.5

## Environment

-   Version used : wallet 3.4.9
-   Operating System and version : Windows 10 pro
![debug](https://user-images.githubusercontent.com/62860630/119774512-45c46900-be90-11eb-944b-9c5806d16640.JPG)
![trace](https://user-images.githubusercontent.com/62860630/119774514-45c46900-be90-11eb-92a3-cac88f4d8e45.JPG)

**Comment by Falbor1** [comment]
I also have this issue
miner runs perfectly and balance is sent to wallet address

last 100% sync was 20210522
Version used : wallet 3.4.9
Operating System and version : Windows 10 pro

**Comment by mehmedin** [comment]
not updating
sync: 98,95 stop  
Version used : wallet 3.4.9
Operating System and version : Windows 10 pro

**Comment by hss78** [comment]
are we lost our coins ? Wallet not updating,its syncs almost 4 hours.

**Comment by mehmedin** [comment]
it's been more than 1 week.

**Comment by zpalmtree** [comment]
You probably need to try syncing with an alternative node. https://docs.turtlecoin.lol/guides/wallets/using-remote-nodes#proton-wallet

If you are having issues with this, you should join our [discord](http://chat.turtlecoin.lol) for assistance.

**Comment by mehmedin** [comment]
tşk

**Comment by Falbor1** [comment]
thanks for this tip
tried an other node and still does not work - I will try to get in touch to solve this on the discord server

**Comment by yuluochengxin** [comment]
> 感谢此提示
> 尝试了另一个节点，但仍然无法正常工作-我将尝试与 Discord 服务器联系以解决此问题

Have you solved your problem？I had the same problem

**Comment by yuluochengxin** [comment]
> thanks for this tip
> tried an other node and still does not work - I will try to get in touch to solve this on the discord server

**Comment by brandonlehmann** [comment]
https://docs.turtlecoin.lol/guides/wallets/restoring-your-wallet-from-a-specific-block-height

**Comment by ExtraHash** [comment]
Has this issue been resolved? It appears to be a node issue from the dev console screenshots

**Comment by Falbor1** [comment]
rescan my proton wallet from height0 and is back to 100% sync again. took some time though

**Comment by ExtraHash** [comment]
Great, thanks for the update
