### ISSUE TITLE
the wallet is not receiving any coins from the miner

### ISSUE THREAD

**Issue by dimitrifernando** [turtlecoin/turtle-wallet-proton#148]
## Expected Behavior
 
I ran the TurtleCoind file 

then i ran the miner.

Miner asked for my wallet addres. I gave it the address i got when i installed the wallet from turtlecoin.lol

Miner says '
Started mining for difficulty of (a number comes here) Good Luck!

This goes on forever

Nothing is coming into the wallet.

It is not receiving coins.

I exit the wallet and re open it. It asks for password. Once i am in the wallet there are still no coins.

So whats going on?

The coind file is also running along with the miner.

I should be seeing the coins come into the wallet  

I am on a Dell Vostro I5 standard laptop, NO GPU,  

Running Windows 10
 
![turtlecoin mining](https://user-images.githubusercontent.com/84901912/119797527-f023a700-bef7-11eb-9cb3-b4109dfdf98c.PNG)

**Comment by orphaner69** [comment]
i have the same problem...herominers says they have sent 2k Turtle  coins to my wallet (same version)no incoming transfers !!! and when i open...it's sync percent is always under %100 above %99...never fully syncs...but before payment it was %100....who is stealing our coins ?!?!?!?

**Comment by brandonlehmann** [comment]
> i have the same problem...herominers says they have sent 2k Turtle coins to my wallet (same version)no incoming transfers !!! and when i open...it's sync percent is always under %100 above %99...never fully syncs...but before payment it was %100....who is stealing our coins ?!?!?!?

This is not the same problem. See: https://docs.turtlecoin.lol/guides/wallets/restoring-your-wallet-from-a-specific-block-height

**Comment by brandonlehmann** [comment]
> ## Expected Behavior
> I ran the TurtleCoind file
> 
> then i ran the miner.
> 
> Miner asked for my wallet addres. I gave it the address i got when i installed the wallet from turtlecoin.lol
> 
> Miner says '
> Started mining for difficulty of (a number comes here) Good Luck!
> 
> This goes on forever
> 
> Nothing is coming into the wallet.
> 
> It is not receiving coins.
> 
> I exit the wallet and re open it. It asks for password. Once i am in the wallet there are still no coins.
> 
> So whats going on?
> 
> The coind file is also running along with the miner.
> 
> I should be seeing the coins come into the wallet
> 
> I am on a Dell Vostro I5 standard laptop, NO GPU,
> 
> Running Windows 10
> 
> ![turtlecoin mining](https://user-images.githubusercontent.com/84901912/119797527-f023a700-bef7-11eb-9cb3-b4109dfdf98c.PNG)

You are solo mining to a local node it appears. You will not get any coins unless you find a block yourself. Have you found a block?

**Comment by orphaner69** [comment]
> > i have the same problem...herominers says they have sent 2k Turtle coins to my wallet (same version)no incoming transfers !!! and when i open...it's sync percent is always under %100 above %99...never fully syncs...but before payment it was %100....who is stealing our coins ?!?!?!?
> 
> This is not the same problem. See: https://docs.turtlecoin.lol/guides/wallets/restoring-your-wallet-from-a-specific-block-height

Thanks....SYNC OK but still no income !!!  nothing in my wallet !!!

**Comment by ExtraHash** [comment]
You're solo mining and haven't hit any blocks. Until you hit a block, you won't receive any TRTL. At 50h/s it will likely take you years to hit a block, I might recommend mining to a pool.
