### ISSUE TITLE
Send Error

### ISSUE THREAD

**Issue by Laqqer** [turtlecoin/turtle-wallet-proton#151]
![Error](https://user-images.githubusercontent.com/12718943/120896606-01bd2b00-c62b-11eb-8a25-6cc7f7563799.jpg)
Not sending the whole turtle is it a bug?

![ERROR3](https://user-images.githubusercontent.com/12718943/120896554-c9b5e800-c62a-11eb-8ae1-0054aeda02cd.jpg)

**Comment by ExtraHash** [comment]
I would recommend trying to re-scan your wallet
