### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by joklin** [turtlecoin/turtle-wallet-proton#152]
## Current Behavior
can't login even though the password is correct
![Untitled](https://user-images.githubusercontent.com/4612446/122640972-8bd9b900-d12c-11eb-886f-98303f83a759.png)

-   Version used : 3.4.9
-   Operating System and version : Windows 10

**Comment by ExtraHash** [comment]
Most likely your wallet file has been corrupted on disk, or possibly you have moved the wallet file. I would recommend restoring from your mnemonic seed.
