### ISSUE TITLE
Trtlcoin wallet balance problem

### ISSUE THREAD

**Issue by tk74** [turtlecoin/turtle-wallet-proton#154]
about 2 months ago i sent trtl from coinex to trtlcoin wallt 3.4.9 , since then then ballance in wallet shows 0 , i sent a ticket to coinex and they told that there was no problem and withdraw was a success , i resrtored the wallet from backup key with a fresh install but again the same problem , another thing is that the syncing on the below part of the wallet never reaches 100% even with diffrent type of nodes , what will u suggest for my problem ? ( i restore wallet on both windows 10 & 8.1 )

**Comment by ExtraHash** [comment]
Try switching to a different node in settings

**Comment by amirbeigi1990** [comment]
i withdrawal trtl coin from coinex to trtl wallet v 3.4.9 yesterday
in coinex the status is sent and coinex has no problem
my balance in trtl wallet is still 0
and wallet sync is 98% . . .
please help
