### ISSUE TITLE
My transactions is failed 

### ISSUE THREAD

**Issue by amiroomega** [turtlecoin/turtle-wallet-proton#169]
after3months my transaction is not received 

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

-   Version used :
-   Operating System and version :

**Comment by amiroomega** [comment]
> Please try resyncing/restoring the wallet. If that does not resolve the issue, please check the explorer for the transaction using the transaction hash; or, contact the sending party to verify that the funds were properly sent to you.

Tanx for reply. But I did restore for many times.and hash is correct and my public address too.but i don't recived yet.turtle's has any online support ?

**Comment by brandonlehmann** [comment]
> > Please try resyncing/restoring the wallet. If that does not resolve the issue, please check the explorer for the transaction using the transaction hash; or, contact the sending party to verify that the funds were properly sent to you.
> 
> Tanx for reply. But I did restore for many times.and hash is correct and my public address too.but i don't recived yet.turtle's has any online support ?

You may try zedwallet from the core package to see if that makes any difference when you resync the wallet. Short of that, the funds may not have been sent to you.

The v1 chain is a privacy-based chain. There's nothing that anyone can do to recover funds if you don't have the private spend and private view key(s) of the wallet in which the funds were sent to.

We advise that you contact the **sender** of the funds to verify that they sent them to the proper address. Unfortunately, we cannot verify this for you.
