### ISSUE TITLE
Align to right amount and balance columns values

### ISSUE THREAD

**Issue by odedgoro** [turtlecoin/turtle-wallet-proton#34]
Align to right amount and balance columns values for better readability.

**Comment by ExtraHash** [comment]
can you explain what you mean by balance columns

**Comment by odedgoro** [comment]
![image](https://user-images.githubusercontent.com/47347196/61222571-a5de1600-a723-11e9-9598-7a41a7d123e3.png)
Align to right
not left
![Uploading image.png…]()

**Comment by ExtraHash** [comment]
this is now in the dev branch as of 447d67f and will be on the next release, good idea btw looks much nicer thanks
