### ISSUE TITLE
support minimizing and closing to system tray

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtle-wallet-proton#35]
I'd like to be able to enable and disable this behavior in settings

**Comment by LithyRiolu** [comment]
https://github.com/kusti8/proton-native/issues/101 - I hope this helps

**Comment by zpalmtree** [comment]
Despite the name, this is using electron+react native, not proton native.

**Comment by LithyRiolu** [comment]
Ah, I see. Thanks for clearing that up

**Comment by ExtraHash** [comment]
I chose the name since the common name among the community for walletshell was "electron wallet", and I intended this to be its successor
