### ISSUE TITLE
conditional validation for dialogs

### ISSUE THREAD

**Issue by 0des** [turtlecoin/turtle-wallet-proton#36]
it doesnt break anything, so i put this under feature request, but it could be a bug too depending how you interpret it. In this case, conditional validation would mean that the user would not see the "success" message unless the transaction produced a tx id or non-err state on completion.

![image](https://user-images.githubusercontent.com/52985253/61477866-defdcc80-a955-11e9-8440-9c70e8b46f7a.png)

`Your transaction was send successfully.` (implies it worked)

`We were not able to submit our request to the daemon. Ensure it is online and not frozen.` (We aren't running the daemon, the default for this program is to use one that's remotely managed. In most cases this phrase would not be relevant.)

BONUS: add some type of big red angry X or something that conveys whether the attempted TX went through or not easily and visually for those that just next-next-next everything.

**Comment by ExtraHash** [comment]
hello, thanks for reporting this, i had it on my to-do list but sort of forgot about it, should be pretty easy to do.

i also notice you are on MacOS, is the wallet working fairly smoothly otherwise? mac testing has been fairly limited

**Comment by 0des** [comment]
It is Linux, Debian

**Comment by ExtraHash** [comment]
ah ok, my mistake. thanks for the report!

**Comment by 0des** [comment]
Great work on the wallet!

**Comment by ExtraHash** [comment]
This error message has been fixed in the dev branch from 0c5163b, it now no longer says anything about a successful transaction and only prints the error message returned by walletbackend
