### ISSUE TITLE
Balance widget does not include locked balance

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-proton#37]
When we send an outgoing transaction, till the transaction is added to a block, the balance displays only the unlocked balance, which may be very different to the total balance.

I suggest we modify this element to always display the full balance, but if a section of the balance is locked, perhaps change the colour to orange.

For bonus points, add an onhover or onclick which displays the locked / unlocked amounts.

**Comment by ExtraHash** [comment]
the incorrect balance portion of this is fixed in  d464323 , however i'm going to add an on hover tooltip showing locked / unlocked balances before closing the issue

**Comment by ExtraHash** [comment]
94eec2b adds the hover tooltip as well as some other visual differences when a balance is locked (lock icon, warning color)
