### ISSUE TITLE
Historical balance is incorrect when a portion of balance is locked

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-proton#38]
When an outgoing transaction has been sent, and a portion of the balance is locked, the 'Balance over time' displays incorrectly.

For example, if we started with 1000 TRTL, sent 100 TRTL which caused 500 TRTL to be locked, the historical balance would display

`500 -> 400` when it should display `1000 -> 900`.

This is likely due to you using the `unlockedBalance` figure to calculate these values, rather than the `unlockedBalance + lockedBalance` figure.

**Comment by Worst-Crypto-Projects** [comment]
_exitscam_

**Comment by ExtraHash** [comment]
this is fixed in  d464323

**Comment by ExtraHash** [comment]
reopening because this apparently is still not fixed by taking both unlocked + locked balance

![image](https://user-images.githubusercontent.com/35851667/61599770-f4932080-abf9-11e9-9ce1-0add3bb9bf72.png)

**Comment by ExtraHash** [comment]
closing this again as it only seems to happen when sending to yourself. still unsure why but it doesn't seem to be a big issue
