### ISSUE TITLE
Compiling for ARM (Raspberry Pi 4B)

### ISSUE THREAD

**Issue by ibrahimk157** [turtlecoin/turtle-wallet-proton#40]
Hello,

Is there any way I could compile this to work on the ARM architecture? Specifically the Raspberry Pi 4B (or even 3B+)? 

Sorry if this sounds like a silly question, I’m a noob when it comes to this stuff!

Thanks!

**Comment by ExtraHash** [comment]
i am not sure if electron-builder will do this with the current configuration, but it might be. can you try following the build instructions on the readme and report back?

**Comment by ibrahimk157** [comment]
I don’t see any building instructions on the readme, unless I overlooked something. 

But again, I’m a noob at this stuff so apologies in advance.

**Comment by ExtraHash** [comment]
No problem, the building instructions are here:

https://github.com/turtlecoin/turtle-wallet-proton/#development-setup-all-platforms

You're going to want to follow the development setup instructions all the way through. The last step, "packaging", will attempt to package the app for the local platform.

**Comment by ibrahimk157** [comment]
Alright perfect! Will give it a try in about half and hour and will update you on the outcome.

Thanks!

**Comment by ibrahimk157** [comment]
It errored out like there is no tomorrow when i reached the step where you run “yarn”. Here’s a paste:
https://pastebin.com/VtPnfJs4

**Comment by ExtraHash** [comment]
alright, thanks. i'll look into if this is possible, I assume it is somehow. i'll set up a DE on my pi a little later today and start screwing with it

**Comment by ExtraHash** [comment]
ah, can you install nodejs version 10 and give it another shot if you get a chance?

**Comment by ibrahimk157** [comment]
Found something interesting... running yarn start actually started it. But yarn package errors out like hell

**Comment by ibrahimk157** [comment]
I have no darn clue how to install specific versions of nodejs lol. I just followed this guide (skip to the installation part): https://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/

**Comment by ExtraHash** [comment]
no sweat, i'll take a look at it later this evening

**Comment by ibrahimk157** [comment]
alright thanks a lot!

**Comment by ExtraHash** [comment]
If you'd like to try it out yourself, you can use `nvm` in order to install a specific version

first remove your current version
`sudo apt remove nodejs`

then install  node version manager (nvm)
`sudo apt install nvm`

follow the on screen prompts if any, then install the latest LTS version of node which is version 10
`nvm install --lts`

if not, no worries like I said i can mess with it later

**Comment by ibrahimk157** [comment]
it said the nvm package wasnt found, so i installed it using this guide: https://github.com/blobsmith/raspberryTestNode/wiki/Node.js-installation-with-nvm-on-Raspberry-pi

Now ill give the rest a shot

**Comment by ibrahimk157** [comment]
here's the outcome: https://pastebin.com/Aug9zLvk

not sure if it's good or not

**Comment by ibrahimk157** [comment]
when i run yarn start it seems to work. but yarn package returns this: https://pastebin.com/xsEB9bpT

**Comment by ExtraHash** [comment]
ah. you got farther than I did last night, my pi kept freezing installing dependencies. i see it's throwing an unsupported architecture error on packaging. you can just run yarn start for now, i'll do some research. if it runs it should package i think so likely just needs a configuration update

**Comment by ibrahimk157** [comment]
Alright. Just out of curiosity, what model rpi do you have?

Also, if you want, I can give you remote access to my rpi if yours won’t behave.

**Comment by ExtraHash** [comment]
raspberry pi b3+, i put the stock raspbian on it

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ibrahimk157** [comment]
Raspbian is what I use too. My Rpi 4B got raspbian buster the day I started using it. However, my 3B+ had stretch and upgrading to buster quite literally took hours!!! So if you’re on stretch, that MIGHT have something to do with it getting stuck (not fully sure, just making assumptions here).

**Comment by ExtraHash** [comment]
no, i was on buster. not sure what happened, the entire kernel locked up when it was building the native dependencies. ill give it another go here in a bit

**Comment by ibrahimk157** [comment]
Interesting... again, if you can’t get it to work on your end, I can always give you remote access to my 4B. We’ll need to choose a time where we’re both online though as I can’t leave that thing on 24/7 (I don’t trust it)

**Comment by ExtraHash** [comment]
i've got it working now, working on a fix

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ibrahimk157** [comment]
Neat! 

P.s. thanks a lot for actually doing your best in getting this working for arm. I’ve requested arm support with many programs before and the devs could’ve cared less.

**Comment by ExtraHash** [comment]
no problem at all, we have ARM compatability on our core software suite so it makes sense for the GUI to have it as well.

**Comment by ExtraHash** [comment]
It looks like electron-builder doesn't support ARM architecture yet unfortunately, I'll have to bring in a different packager in order to support it. Will leave this open and do a bit more research

**Comment by ibrahimk157** [comment]
Alright thanks a lot!

**Comment by ExtraHash** [comment]
with the newest release, we now have an AppImage for aarmv7. Can you please download the aarmv7 AppImage from the [releases](https://github.com/turtlecoin/turtle-wallet-proton) page and let me know how it works for you? Thanks

**Comment by ibrahimk157** [comment]
It works!!! I really can’t thank you enough!!!!

**Comment by ExtraHash** [comment]
no problem, thanks for taking the time to make the feature request
