### ISSUE TITLE
Clicking the 'X' in Windows Does Not Close The App

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-proton#65]
Clicking the 'X' in the top right hand of the corner of the application should close the app; or, if the desired result is to minimize to the system tray, that option should be configurable **and** if enabled, displays a system tray notification saying "I've minimized to the system tray" or something to that effect. Here I thought my test wallet was closed for days but it was open -- without a password -- in my system tray for over a week. This isn't very secure.

**Comment by ExtraHash** [comment]
a lot of apps these days close to the system tray by default (Discord for example). I have already been working on a change however that will lock the wallet with a password after a period of inactivity... perhaps this would alleviate your concern? I can also make it a configurable setting but adding a tray notification seems unnecessary to me

**Comment by zpalmtree** [comment]
I would +1 making it configurable - Things minimizing to tray on 'X' is one of my pet peeves.

**Comment by ExtraHash** [comment]
no problem making a tickbox to enable/disable behavior, my main concern with the tray notification (besides it seeming superfluos) is that it's not cross platform

**Comment by BrandonT42** [comment]
I agree with the others... IMO, closing when you click the close button should be default. Minimizing to the tray should be optional. If it's set up that way, a notification isn't even really needed.
