### ISSUE TITLE
0.0.25 does not sync

### ISSUE THREAD

**Issue by old-greywolf** [turtlecoin/turtle-wallet-proton#67]
i do not understanbd those format things.  sorry.  i just want to report a problem with the latest update.  the previous version prompted me to download an update.  i clicked, and got an error on the github page, and a file downloaded.  i posted the error in Discord.  now the updated version does not sync.  it opens, and is red for 5 to 7 minutes or so, then changes to yellow and never gets past 99.12%

- Version used : 0.0.25
- Operating System and version :  Windows 10 Pro N, Version 1803, OS build 17134.950

**Comment by ExtraHash** [comment]
can you try selecting a different node? nothing has changed as far as the sync process goes

**Comment by old-greywolf** [comment]
yes, different node works.  thanks.
