### ISSUE TITLE
Add Random Payment ID Generation (and Integrated Address Generation) To the Receive Screen

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-proton#69]

**Comment by brandonlehmann** [comment]
What do you mean **low priority**? Versus #62 ?

**Comment by ExtraHash** [comment]
means not on this release cycle but the next

**Comment by ExtraHash** [comment]
compared to #72 and #71 are what are being focused on for this release in addition to what is already done

**Comment by ExtraHash** [comment]
this has been added in 74feab6, if you get a chance please check it out and let me know your thoughts
