### ISSUE TITLE
Display Payment ID On Incoming Transactions

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-proton#70]

**Comment by brandonlehmann** [comment]
What do you mean **low priority**? Versus #62 or #64 ?

**Comment by ExtraHash** [comment]
vs #72 and #71, also this was also something I had in mind when I made #47

**Comment by ExtraHash** [comment]
This is implemented in 9c671e, please check it out if you get the time and let me know your feedfback
