### ISSUE TITLE
bug: cancel still attempts to send the tx when not synced

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtle-wallet-proton#73]
## Expected Behavior

when clicking cancel, should not be prompting more to click ok/cancel - ought to abort sending.

## Current Behavior

send tx before sync, get a msg asking if want to send? click cancel and get prompted to send anyway with a different msg.

![image](https://user-images.githubusercontent.com/317/64457779-a86b5380-d147-11e9-8ccc-1a9f1f7d2e7b.png)

click cancel

![image](https://user-images.githubusercontent.com/317/64457794-b325e880-d147-11e9-84c5-caf193982833.png)

## Steps to Reproduce (for bugs)

1. open wallet that is not in sync

2. send a tx

3. get msg's as above

## Your Environment

- Version used : 0.0.25
- Operating System and version : win10

**Comment by ExtraHash** [comment]
resolved in  0545da4
