### ISSUE TITLE
Confirm Transaction Screen Choices Feel Funky

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-proton#76]
![image](https://user-images.githubusercontent.com/20562132/64479331-652ed600-d183-11e9-8ccf-eab16e90bdbe.png)

The prompt asks, "Do you wish to proceed?" which is a **Yes** or **No** question, not **OK** or **Cancel**

**Comment by ExtraHash** [comment]
I disagree, OK is a perfectly valid response to that question

**Comment by brandonlehmann** [comment]
https://medium.com/@wutronic/which-to-choose-cancel-ok-ok-cancel-or-yes-no-ec119861eb9b

https://ux.stackexchange.com/questions/9946/should-i-use-yes-no-or-ok-cancel-on-my-message-box

https://news.ycombinator.com/item?id=5018918

https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/

Will accept change from **OK** to **Send** but **OK** sucks.

**Comment by ExtraHash** [comment]
All of those links seem to say not to use yes/no...

```so In short, don’t use Yes/No unless it is already standardized. Lean on side of explicitly stating intent whenever possible. ```

OK / Cancel is an OS standard, we should use it

**Comment by brandonlehmann** [comment]
> OK / Cancel is an OS standard, we should use it

Do you have a source for this misinformation?

**Comment by ExtraHash** [comment]
The links you provided cover it well

**Comment by brandonlehmann** [comment]
> The links you provided cover it well

![fa6c6fa2-04e2-445e-834d-f31e6b599127](https://user-images.githubusercontent.com/20562132/64479410-cc00bf00-d184-11e9-898b-858a7ed4501b.png)
![b18eb883-8dea-43a5-9e0c-ef809ddc18b4](https://user-images.githubusercontent.com/20562132/64479413-cdca8280-d184-11e9-9cd4-1b327290c10d.png)
![b8bd3e20-9ea9-4ceb-939c-3adb392266d2-350x184](https://user-images.githubusercontent.com/20562132/64479415-d0c57300-d184-11e9-9533-71cbecdd4fec.png)
![97de1c23-a09b-40ff-a1a5-807a2d5506e0](https://user-images.githubusercontent.com/20562132/64479417-d28f3680-d184-11e9-8b4e-9bac686c095f.png)
