### ISSUE TITLE
Add Copy Button on Transaction Complete Screen

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-proton#77]
![image](https://user-images.githubusercontent.com/20562132/64479341-9c04ec00-d183-11e9-8692-2c61875d8430.png)

I cannot select the transaction has upon sending, perhaps add a copy button or some other way for the user to easily copy the transaction hash instead of making them return to the wallet screen and then trying to find it.

**Comment by ExtraHash** [comment]
It takes you to the transaction screen automatically after sending
