### ISSUE TITLE
Find node... link goes to dead page

### ISSUE THREAD

**Issue by old-greywolf** [turtlecoin/turtle-wallet-proton#78]
The link to Find node... goes to a page that has not displayed any nodes for several days:
https://trtl.nodes.pub/.

To find nodes that are up, another page that works is:
https://trtl-stat.mine2gether.com/d/ePIVQZTik/turtle-network

- Version used :  0.0.25
- Operating System and version :  Windows Pro 10 N, Version 1803, OS build 17134.950

**Comment by ExtraHash** [comment]
Hi grey, 
     Thanks for the report. I've already changed this link on the dev branch to point to the new node monitor on the block explorer, so it will be updated in the next version release (which should be very soon)
