### ISSUE TITLE
Add dark mode setting

### ISSUE THREAD

**Issue by odedgoro** [turtlecoin/turtle-wallet-proton#8]
![image](https://user-images.githubusercontent.com/47347196/60735001-6ca2ea80-9f5a-11e9-9895-59a53e25d530.png)

**Comment by ExtraHash** [comment]
does look cool, i'll work on it

**Comment by ExtraHash** [comment]
this has been added in [v0.0.17](https://github.com/turtlecoin/turtle-wallet-proton/releases/tag/v0.0.17), binaries should be up as soon as travis builds them
