### ISSUE TITLE
CSV export saves with the wrong filename

### ISSUE THREAD

**Issue by darnti** [turtlecoin/turtle-wallet-proton#87]
## Expected Behavior
File should be saved with the name typed in the export dialog.

## Current Behavior
The filename is always appended with ".csv". If you try to save a file named "export.txt", it will instead be saved as "export.txt.csv." If you try to save a file named "export.csv" that already exists, and you attempt to overwrite it, a *new* file is saved called "export.csv.csv."

## Steps to Reproduce (for bugs)

Under dialog at Tools->Export to CSV:
* Choose any file name
* Save as type: All Files (*.*)

## Your Environment

- Version used : 0.0.27
- Operating System and version : Windows 10 Home 10.0.18362 Build 18362

**Comment by ExtraHash** [comment]
this has been resolved as of c85a32c and will be fixed on the next version release
