### ISSUE TITLE
Sending from Proton wallet to KuCoin... just get spinning green "send" button

### ISSUE THREAD

**Issue by MasterJedi007** [turtlecoin/turtle-wallet-proton#89]
## Expected Behavior

After you click "send", windows pops up to confirm, then new window confirms the funds have been sent to your send address

## Current Behavior
Click send, then click confirm in pop window, then the 'send' button in the wallet send screen just has spinning circle of death, and nothing happens... if you click the "Wallet" button the send does not show, as if it never went thru.

## Your Environment

- Version used : Proton v1.0.0
- Operating System and version : Micro$oft Windowz 10 Enterpri$e

**Comment by ExtraHash** [comment]
Does this happen every time you make a transaction?

Check in Settings, under "Node". What remote node are you connected to?

If you leave the transaction while it is spinning, it never eventually shows a modal saying the transaction did / did not broadcast?

**Comment by MasterJedi007** [comment]
Out of the 13 times I have tried to make a send attempt, only 1 transfer was successful. I am currently connected to the blockapi.turtlepay.io:443 node. It just continues to spin until the app locks, was I re-open or unlock it returns to the wallet screen and shows no send.

**Comment by ExtraHash** [comment]
Reviewing the logs from the cache api, it appears you probably have some bad inputs in your wallet. Please perform a full rescan which should alleviate the issue.

**Comment by ExtraHash** [comment]
The wallet should be displaying a transaction error message as a popup modal, and unfortunately I am not able to reproduce it just spinning forever on my windows machine

**Comment by MasterJedi007** [comment]
Where are the log files store?

**Comment by ExtraHash** [comment]
if you have the walletbackend loglevel setting set to something other than DISABLED, the log file will be stored at C:/Users/username/.protonwallet/logs/wallet-backend.log 

You can try setting it to DEBUG, then doing a transaction and uploading the log file here afterwards

**Comment by MasterJedi007** [comment]
Here what I believe your looking for... 
[2019-10-10 13:44:16.154] [debug] Wallet synced! Wallet height: 1918306, Network height: 1918305
[2019-10-10 13:45:01.894] [debug] Sending transaction: Amount: 1776980 Address ----MY ADDRESS---- PID: ----MY NOTES-----  
[2019-10-10 13:45:46.504] [debug] Wallet is no longer synced! Wallet height: 1918308, Network height: 1918309
[2019-10-10 13:45:56.549] [debug] Wallet synced! Wallet height: 1918309, Network height: 1918309

Look like the wallet is no longer synced once the transaction is placed....

**Comment by ExtraHash** [comment]
No, sorry, that's not the log I need. Go to settings > wallet, turn the `WalletBackend LogLevel` to DEBUG, and then the file will be located at C:/Users/username/.protonwallet/logs/wallet-backend.log

**Comment by MasterJedi007** [comment]
OK... got it now I believe;

[Thu, 10 Oct 2019 20:26:27 GMT] [Debug]: Finished processing block 1918613
[Thu, 10 Oct 2019 20:26:27 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:26:27 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:26:37 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:26:37 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:26:38 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:26:47 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:26:47 GMT] [Info] [Transactions]: Performing auto optimization
[Thu, 10 Oct 2019 20:26:47 GMT] [Info] [Transactions]: Auto optimization complete
[Thu, 10 Oct 2019 20:26:48 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:26:48 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:26:57 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:26:57 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:26:57 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:26:58 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:26:59 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:27:07 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:27:09 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:27:11 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:27:17 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:27:21 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:27:27 GMT] [Info] [Daemon]: Failed to get wallet sync data: RequestError: Error: ESOCKETTIMEDOUT
[Thu, 10 Oct 2019 20:27:27 GMT] [Debug]: Zero blocks received from daemon, possibly fully synced
[Thu, 10 Oct 2019 20:27:27 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:27:28 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:27:28 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:27:37 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:27:37 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:27:37 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:27:47 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:27:47 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:27:47 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:27:57 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:27:58 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:27:58 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:27:58 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:27:58 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:28:08 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:28:08 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:28:08 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:28:18 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:28:18 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:28:18 GMT] [Debug]: Zero blocks received from daemon, fully synced

Hope that helps!

**Comment by ExtraHash** [comment]
Did you try to send a transaction while it was logging? This log file doesn't show any transactions attempted

**Comment by MasterJedi007** [comment]
I started with a fresh log file, here is the full file ( I attempted 2 transfers);

[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918630
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Approximate ram usage of stored blocks: 362.41 KB, fetching more.
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918630
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918631
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918631
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918632
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918632
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918634
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918634
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918637
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918637
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918640
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Approximate ram usage of stored blocks: 105.24 KB, fetching more.
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918640
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918641
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918641
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918643
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918643
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918645
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918645
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918654
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918654
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918655
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918655
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918660
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Approximate ram usage of stored blocks: 2.04 KB, fetching more.
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918660
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Processing block 1918661
[Thu, 10 Oct 2019 20:46:22 GMT] [Debug]: Finished processing block 1918661
[Thu, 10 Oct 2019 20:46:23 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:46:23 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:46:32 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:46:32 GMT] [Info] [Transactions]: Performing auto optimization
[Thu, 10 Oct 2019 20:46:32 GMT] [Info] [Transactions]: Auto optimization complete
[Thu, 10 Oct 2019 20:46:33 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:46:33 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:46:42 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:46:43 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:46:52 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:46:52 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:46:52 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:46:53 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:47:02 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:47:03 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:47:03 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:47:12 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:47:13 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:47:13 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:47:22 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:47:22 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:47:22 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:47:23 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:47:23 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:47:32 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:47:33 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:47:33 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:47:42 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:47:43 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:47:43 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:47:52 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:47:52 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:47:52 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:47:53 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:48:02 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:48:03 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:48:13 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:48:13 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:48:13 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:48:22 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:48:22 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:48:23 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:48:23 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:48:23 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:48:33 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:48:33 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:48:33 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:48:43 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:48:43 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:48:43 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:48:52 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:48:52 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:48:53 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:48:53 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:48:54 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:49:03 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:49:04 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:49:04 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:49:13 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:49:14 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:49:14 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Thu, 10 Oct 2019 20:49:23 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Thu, 10 Oct 2019 20:49:23 GMT] [Debug] [Transactions]: Checking locked transactions
[Thu, 10 Oct 2019 20:49:23 GMT] [Debug] [Daemon]: Updating daemon info...
[Thu, 10 Oct 2019 20:49:24 GMT] [Debug]: No blocks stored, attempting to fetch more.
[Thu, 10 Oct 2019 20:49:24 GMT] [Debug]: Zero blocks received from daemon, fully synced

**Comment by MasterJedi007** [comment]
Would a re-install be advised?

**Comment by ExtraHash** [comment]
can you try booting it up again with the LogLevel at TRACE instead of DEBUG and sending a few more transactions? I can't see anything in the log file about it even attempting to send the transactions, which is very odd

**Comment by MasterJedi007** [comment]
[wallet-backend.log](https://github.com/turtlecoin/turtle-wallet-proton/files/3714624/wallet-backend.log)

**Comment by ExtraHash** [comment]
I guess you can try a reinstall and see if that fixes the issue, for some reason it seems as though it's never even attempting to send the transaction.

I've been trying to reproduce on Win10 and am unable to reproduce this bug so I'm not sure what's going on.

**Comment by MasterJedi007** [comment]
OK, no worries, I'll try to completely remove all folder and files and let it re-sync and then get back with you.

**Comment by ExtraHash** [comment]
@brandonlehmann looked over the log file as well and noticed some issues that appear to be due to the network congestion and resultant forking we experienced a few days ago. It looks like the wallet did not detect a chain reorganization correctly and is stuck on the wrong chain. A resync should fix the issue you're having

**Comment by ExtraHash** [comment]
Hello, did resyncing resolve your issue?

**Comment by ExtraHash** [comment]
Hello, I still haven't heard back so I'm going to assume the resync fixed your issue. Thanks for the log, I believe we found the root cause of what was going on. I'm closing this for now, but feel free to comment again if it needs to be reopened.

**Comment by MasterJedi007** [comment]
Sorry for the delay, had to go out of town, but I was unable to send once I re-synced. Which took some time to re-download the blockchain. But it is working now! Thank you for your help!

**Comment by ExtraHash** [comment]
No sweat, thanks for following up!
