### ISSUE TITLE
Wrong balance

### ISSUE THREAD

**Issue by odedgoro** [turtlecoin/turtle-wallet-proton#9]
Showing wrong balance at the bottom
![image](https://user-images.githubusercontent.com/47347196/60739239-df679200-9f69-11e9-8f53-5101c9a05584.png)

**Comment by ExtraHash** [comment]
can you describe if you did anything specific for this to occur? is it always incorrect?

**Comment by odedgoro** [comment]
Didn't do anything. Just let it fully sync. At some point bottom balance just stopped updating.

**Comment by odedgoro** [comment]
just started new sync and bottom balance remains at 0.
![image](https://user-images.githubusercontent.com/47347196/60750437-02696480-9fb1-11e9-8a7c-f60e9297e6ed.png)

**Comment by odedgoro** [comment]
Noticed that after several switching from window to window wallet/send /recive bottom balance gets updated and after that remains stuck on last updated balance.

**Comment by ExtraHash** [comment]
alright, will investigate

**Comment by ExtraHash** [comment]
this has been fixed in [v0.0.7-beta](https://github.com/turtlecoin/turtle-wallet-proton/releases/tag/v0.0.7-beta)
