### ISSUE TITLE
1.1.0 RC4

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtle-wallet-proton#96]
# Release Candidate

## System Info:

<b>OS Used for Tests:</b> Arch Linux

## Creation

- [x] Loads the internal config when local config not present

- [x] Can create a wallet

- [x] Can import a wallet with keys

- [x] Can import a wallet with seed

- [x] Import scan height exact height works

### General Operation

- [x] Wallet can sync

- [x] Wallet can receive a transaction

- [x] Coin price is loaded from API

- [x] Notifications are received when transaction is received (if enabled)

- [x] Wallet sync process is saved on close

- [x] Can login with password

- [x] Lock button works

- [x] Lock button only shows up when password enabled

- [x] All operations in the native menus work 

- [x] Operations in the native menu that should require login do not work unless logged in

- [x] Changing password works

### Backup

- [x] Seed is not displayed when wallet is not mnemonic

### Transferring

- [x] Wallet can send a transaction

- [x] Balance is correctly locked after transaction

- [x] Cannot send negative amount

- [x] Network fee is correctly displayed

- [x] Receiver receives transaction

## Transactions Screen

- [x] Incoming transactions are displayed

- [x] Outgoing transactions are displayed

- [x] Transaction extended details are correct

- [x] Can view transaction on block explorer

- [x] Timestamps of transactions are correct

## Send Screen

- [x] Send all works

- [x] Generate random payment ID works

## Receive Screen

- [x] Copy to clipboard works

- [x] Generate integrated address works

- [x] Defining a custom payment ID and generating integrated address works

## Address Book Screen

- [x] Can add a contact via address book screen

- [x] Cannot create an existing contact

- [x] Contacts are retained after closing application

- [x] Can send to specific contact from address book screen (paper plane icon) 

- [x] Can delete contact

## Terminal Screen

- [x] Displays backend log if loglevel is not DISABLED

- [x] Displays TurtleCoind log output if a log file is selected and tail is enabled

## Search Screen (access by searching at the top right)

- [x] Can search for an address book contact

- [x] Can search for transaction hash

- [x] Can search for a payment ID

- [x] Can search for a block height

- [x] Can search for settings **(if some keyword does not turn up a result you'd expect, please let me know so I can add it as a keyword)**

## Settings

- [x] Preferences are loaded when closing/reopening

- [x] Wallet remembers last settings page and opens it again (unless navigating from searched setting)

### Node Settings

- [x] Changing node works

- [x] Tailing turtlecoind log file works

### Wallet Settings

- [x] Reset from scan height works

- [x] Reset from scan height of zero works

- [x] Scan coinbase transaction toggle works

- [x] Changing walletbackend loglevel works

### Display Settings

- [x] Currency swapping works correctly (click your balance to toggle currencies)

- [x] Light mode works

- [x] Dark mode works

### Security Settings

- [x] Setting autolock interval works

- [x] Disabling autolock works 

- [x] Backup button triggers backup modal

- [x] Change wallet password navigates to change password screen

### Platform Settings

- [x] Disabling notifications works correctly

- [x] Close to tray toggle works

**Comment by ExtraHash** [comment]
# Release Candidate

## Creation

- [ ] Loads the internal config when local config not present

- [ ] Can create a wallet

- [ ] Can import a wallet with keys

- [ ] Can import a wallet with seed

- [ ] Import scan height exact height works

## Wallet

### General Operation

- [ ] Wallet can sync

- [ ] Wallet can receive a transaction

- [ ] Coin price is loaded from API

- [ ] Notifications are received when transaction is received (if enabled)

- [ ] Wallet sync process is saved on close

- [ ] Can login with password

- [ ] Lock button works

- [ ] Lock button only shows up when password enabled

- [ ] All operations in the native menus work 

### Backup

- [ ] Seed is not displayed when wallet is not mnemonic

### Transferring

- [ ] Wallet can send a transaction

- [ ] Balance is correctly locked after transaction

- [ ] Cannot send negative amount

- [ ] Network fee is correctly displayed

- [ ] Receiver receives transaction

## Transactions Screen

- [ ] Incoming transactions are displayed

- [ ] Outgoing transactions are displayed

- [ ] Transaction extended details are correct

- [ ] Can view transaction on block explorer

- [ ] Timestamps of transactions are correct

## Send Screen

- [ ] Send all works

- [ ] Generate random payment ID works

## Receive Screen

- [ ] Copy to clipboard works

- [ ] Generate integrated address works

- [ ] Defining a custom payment ID and generating integrated address works

## Address Book Screen

- [ ] Can add a contact via address book screen

- [ ] Cannot create an existing contact

- [ ] Contacts are retained after closing application

## Terminal Screen

- [ ] Displays backend log if loglevel is not DISABLED

- [ ] Displays TurtleCoind log output if a log file is selected and tail is enabled

## Search Screen (access by searching at the top right)

- [ ] Can search for an address book contact

- [ ] Can search for transaction hash

- [ ] Can search for a payment ID

- [ ] Can search for a block height

- [ ] Can search for settings **(if some keyword does not turn up a result you'd expect, please let me know so I can add it as a keyword)**

## Settings

- [ ] Preferences are loaded when closing/reopening

- [ ] Wallet remembers last settings page and opens it again (unless navigating from searched setting)

### Node Settings

- [ ] Changing node works

- [ ] Tailing turtlecoind log file works

### Wallet Settings

- [ ] Reset from scan height works

- [ ] Reset from scan height of zero works

- [ ] Changing walletbackend loglevel works

### Display Settings

- [ ] Currency swapping works correctly (click your balance to toggle currencies)

- [ ] Light mode works

- [ ] Dark mode works

### Security Settings

- [ ] Setting autolock interval works

- [ ] Disabling autolock works 

- [ ] Backup button triggers backup modal

- [ ] Change wallet password navigates to change password screen

## Platform Settings

- [ ] Disabling notifications works correctly

- [ ] Close to tray toggle works




- [ ] GitHub link works correctly

- [ ] Changing password works

**Comment by ExtraHash** [comment]
All tests passed

**Comment by old-greywolf** [comment]
---
name: Release candidate
about: Open a new RC checklist issue.
labels: 'release candidate'
---

# Release Candidate

## System Info:

<b>OS Used for Tests:</b> <macOS Catalina, Version 10.15>
<b>as of:</b>  <20:30, 10/29/19>

## Creation

- [x] Loads the internal config when local config not present

- [x] Can create a wallet

- [ ] Can import a wallet with keys

- [x] Can import a wallet with seed

- [x] Import scan height exact height works

## Wallet

### General Operation

- [ ] Wallet can sync

- [ ] Wallet can receive a transaction

- [ ] Coin price is loaded from API

- [ ] Notifications are received when transaction is received (if enabled)

- [ ] Wallet sync process is saved on close

- [ ] Can login with password

- [x] Lock button works

- [ ] Lock button only shows up when password enabled

- [ ] All operations in the native menus work

- [ ] Operations in the native menu that should require login do not work unless logged in

- [ ] Changing password works

### Backup

- [ ] Seed is not displayed when wallet is not mnemonic

### Transferring

- [ ] Wallet can send a transaction

- [ ] Balance is correctly locked after transaction

- [ ] Cannot send negative amount

- [ ] Network fee is correctly displayed

- [ ] Receiver receives transaction

## Transactions Screen

- [ ] Incoming transactions are displayed

- [ ] Outgoing transactions are displayed

- [ ] Transaction extended details are correct

- [ ] Can view transaction on block explorer

- [ ] Timestamps of transactions are correct

## Send Screen

- [ ] Send all works

- [ ] Generate random payment ID works

## Receive Screen

- [ ] Copy to clipboard works

- [ ] Generate integrated address works

- [ ] Defining a custom payment ID and generating integrated address works

## Address Book Screen

- [ ] Can add a contact via address book screen

- [ ] Cannot create an existing contact

- [ ] Contacts are retained after closing application

- [ ] Can send to specific contact from address book screen (paper plane icon)

- [ ] Can delete contact

## Terminal Screen

- [ ] Displays backend log if loglevel is not DISABLED

- [ ] Displays TurtleCoind log output if a log file is selected and tail is enabled

## Search Screen (access by searching at the top right)

- [ ] Can search for an address book contact

- [ ] Can search for transaction hash

- [ ] Can search for a payment ID

- [ ] Can search for a block height

- [ ] Can search for settings **(if some keyword does not turn up a result you'd expect, please let me know so I can add it as a keyword)**

## Settings

- [ ] Preferences are loaded when closing/reopening

- [ ] Wallet remembers last settings page and opens it again (unless navigating from searched setting)

### Node Settings

- [ ] Changing node works

- [ ] Tailing turtlecoind log file works

### Wallet Settings

- [ ] Reset from scan height works

- [ ] Reset from scan height of zero works

- [ ] Scan coinbase transaction toggle works

- [ ] Changing walletbackend loglevel works

### Display Settings

- [ ] Currency swapping works correctly (click your balance to toggle currencies)

- [ ] Light mode works

- [ ] Dark mode works

### Security Settings

- [ ] Setting autolock interval works

- [ ] Disabling autolock works

- [ ] Backup button triggers backup modal

- [ ] Change wallet password navigates to change password screen

## Platform Settings

- [ ] Disabling notifications works correctly

- [ ] Close to tray toggle works

**Comment by old-greywolf** [comment]
---
name: Release candidate
about: Open a new RC checklist issue.
labels: 'release candidate'
---

# Release Candidate

## System Info:

<b>OS Used for Tests:</b> Windows 10 Pro N, Version 1803, OS build 17134.1069
<b>as of:</b>  21:15, 10/29/19

## Creation

- [x] Loads the internal config when local config not present

- [x] Can create a wallet

- [ ] Can import a wallet with keys

- [x] Can import a wallet with seed

- [x] Import scan height exact height works

## Wallet

### General Operation

- [x] Wallet can sync

- [x] Wallet can receive a transaction

- [ ] Coin price is loaded from API

- [x] Notifications are received when transaction is received (if enabled)

- [x] Wallet sync process is saved on close

- [x] Can login with password

- [x] Lock button works

- [ ] Lock button only shows up when password enabled

- [ ] All operations in the native menus work

- [ ] Operations in the native menu that should require login do not work unless logged in

- [x] Changing password works

### Backup

- [ ] Seed is not displayed when wallet is not mnemonic

### Transferring

- [x] Wallet can send a transaction

- [x] Balance is correctly locked after transaction

- [ ] Cannot send negative amount

- [ ] Network fee is correctly displayed

- [x] Receiver receives transaction

## Transactions Screen

- [x] Incoming transactions are displayed

- [x] Outgoing transactions are displayed

- [ ] Transaction extended details are correct

- [ ] Can view transaction on block explorer

- [ ] Timestamps of transactions are correct

## Send Screen

- [ ] Send all works

- [x] Generate random payment ID works

## Receive Screen

- [ ] Copy to clipboard works

- [ ] Generate integrated address works

- [ ] Defining a custom payment ID and generating integrated address works

## Address Book Screen

- [x] Can add a contact via address book screen

- [ ] Cannot create an existing contact

- [ ] Contacts are retained after closing application

- [ ] Can send to specific contact from address book screen (paper plane icon)

- [x] Can delete contact

## Terminal Screen

- [ ] Displays backend log if loglevel is not DISABLED

- [ ] Displays TurtleCoind log output if a log file is selected and tail is enabled

## Search Screen (access by searching at the top right)

- [x] Can search for an address book contact

- [x] Can search for transaction hash

- [ ] Can search for a payment ID

- [x] Can search for a block height

- [ ] Can search for settings **(if some keyword does not turn up a result you'd expect, please let me know so I can add it as a keyword)**

## Settings

- [ ] Preferences are loaded when closing/reopening

- [ ] Wallet remembers last settings page and opens it again (unless navigating from searched setting)

### Node Settings

- [x] Changing node works

- [ ] Tailing turtlecoind log file works

### Wallet Settings

- [ ] Reset from scan height works

- [ ] Reset from scan height of zero works

- [ ] Scan coinbase transaction toggle works

- [ ] Changing walletbackend loglevel works

### Display Settings

- [ ] Currency swapping works correctly (click your balance to toggle currencies)

- [x] Light mode works

- [x] Dark mode works

### Security Settings

- [ ] Setting autolock interval works

- [ ] Disabling autolock works

- [ ] Backup button triggers backup modal

- [x] Change wallet password navigates to change password screen

## Platform Settings

- [ ] Disabling notifications works correctly

- [ ] Close to tray toggle works

**Comment by old-greywolf** [comment]
---
name: Release candidate
about: Open a new RC checklist issue.
labels: 'release candidate'
---

# Release Candidate

## System Info:

<b>OS Used for Tests:</b>  Ubuntu 18.04.3 linux 5.0.0-32-generic
<b>as of:</b>  22:00, 10/30/19

## Creation

- [x] Loads the internal config when local config not present

- [x] Can create a wallet

- [x] Can import a wallet with keys

- [x] Can import a wallet with seed

- [x] Import scan height exact height works

## Wallet

### General Operation

- [ ] Wallet can sync

- [ ] Wallet can receive a transaction

- [ ] Coin price is loaded from API

- [ ] Notifications are received when transaction is received (if enabled)

- [ ] Wallet sync process is saved on close

- [x] Can login with password

- [x] Lock button works

- [x] Lock button only shows up when password enabled

- [ ] All operations in the native menus work

- [ ] Operations in the native menu that should require login do not work unless logged in

- [x] Changing password works

### Backup

- [ ] Seed is not displayed when wallet is not mnemonic

### Transferring

- [ ] Wallet can send a transaction

- [ ] Balance is correctly locked after transaction

- [ ] Cannot send negative amount

- [ ] Network fee is correctly displayed

- [ ] Receiver receives transaction

## Transactions Screen

- [x] Incoming transactions are displayed

- [x] Outgoing transactions are displayed

- [x] Transaction extended details are correct

- [x] Can view transaction on block explorer

- [x] Timestamps of transactions are correct

## Send Screen

- [ ] Send all works

- [x] Generate random payment ID works

## Receive Screen

- [x] Copy to clipboard works

- [x] Generate integrated address works

- [x] Defining a custom payment ID and generating integrated address works

## Address Book Screen

- [x] Can add a contact via address book screen

- [x] Cannot create an existing contact

- [x] Contacts are retained after closing application

- [x] Can send to specific contact from address book screen (paper plane icon)

- [x] Can delete contact

## Terminal Screen

- [ ] Displays backend log if loglevel is not DISABLED

- [ ] Displays TurtleCoind log output if a log file is selected and tail is enabled

## Search Screen (access by searching at the top right)

- [x] Can search for an address book contact

- [x] Can search for transaction hash

- [x] Can search for a payment ID

- [x] Can search for a block height

- [x] Can search for settings **(if some keyword does not turn up a result you'd expect, please let me know so I can add it as a keyword)**

## Settings

- [ ] Preferences are loaded when closing/reopening

- [ ] Wallet remembers last settings page and opens it again (unless navigating from searched setting)

### Node Settings

- [x] Changing node works

- [ ] Tailing turtlecoind log file works

### Wallet Settings

- [ ] Reset from scan height works

- [ ] Reset from scan height of zero works

- [ ] Scan coinbase transaction toggle works

- [ ] Changing walletbackend loglevel works

### Display Settings

- [x] Currency swapping works correctly (click your balance to toggle currencies)

- [x] Light mode works

- [x] Dark mode works

### Security Settings

- [x] Setting autolock interval works

- [x] Disabling autolock works

- [x] Backup button triggers backup modal

- [x] Change wallet password navigates to change password screen

## Platform Settings

- [x] Disabling notifications works correctly

- [ ] Close to tray toggle works
